title: Mrinal Mondal 
logo: "/images/self.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Product Development Engineer 
  <br><br>
  Learning and Evolving 
  <br><br>
  <a href="https://www.linkedin.com/in/mrinal-kanti-mondal-2abb3343/"  target="_blank">@LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here